---
- hosts: all
  sudo: no
  
  tasks:
  - name: download composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer
    tags: composer

  - name: install composer
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
    args:
      creates: /usr/local/bin/composer
    become: yes
    become_user: muthu
    tags: composer

  - name: rename composer.phar to composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    args:
      creates: /usr/local/bin/composer
    tags: composer

  - name: make composer executable
    file: 
      path: /usr/local/bin/composer
      mode: a+x
      state: file
    tags: composer

  - composer:
     command: install
     working_dir: /home/muthu/testproject/workcicd/peptide
  
  - name: Set download dir permissions
    file: path=/home/muthu/testproject/workcicd/peptide/vendor owner=www-data group=www-data mode=g+rwX recurse=yes
#    working_dir: /usr/local/peptide
